app/models.py
from app import db
from datetime import datetime
import re


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                     )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())
    user = db.Column(db.Integer)

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)

    def to_dict(self):
        dict = {
        'id': self.id,
        'title': self.title,
        'body': self.body,
        'slug': self.slug,
        'created': str(self.created),
        'user': self.user
        }
        return dict

class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return '<Tag id: {}, name: {}>'.format(self.id, self.name)

    def to_dict(self):
        dict = {
        'id': self.id,
        'name': self.name,
        'slug': self.slug,
        }
        return dict

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    surname = db.Column(db.String(100))
    city = db.Column(db.String(100))
    email = db.Column(db.String(100))
    created_account = db.Column(db.DateTime, default=datetime.now())

    def __repr__(self):
        return '<User id: {}, name: {}, surname: {}>'.format(self.id, self.name, self.surname)

    def to_dict(self):
        dict = {
        'id': self.id,
        'name': self.name,
        'surname': self.surname,
        'city': self.city,
        'email': self.email,
        'created_account': str(self.created_account)
        }
        return dict

app/posts/forms.py
from wtforms import Form, StringField, TextAreaField

class PostForm(Form):
	title=StringField('Название поста')
	body=TextAreaField('Текст поста')

app/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

app/main.py
from app import app
import psycopg2
import view
from app import db
from posts.blueprint import posts
import api_post
import api_user
import api_tag

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
	app.run(debug=True)

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template
from models import Post, Tag
from flask import request
from .forms import PostForm
from app import db
from flask import redirect
from flask import url_for

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/create', methods=['POST','GET'])
def create_post():
	if request.method=='POST':
		title=request.form['title']
		body=request.form['body']

		try:
			post = Post(title=title, body=body)
			db.session.add(post)
			db.session.commit()
		except:
			print('Something wrong')
		return redirect(url_for('posts.index'))

	form = PostForm()
	tags =Tag.query.all()
	return render_template('posts/create_post.html', form=form, tags=tags)

@posts.route('/')
def index():
	q=request.args.get('q')
	result="null"
	if q:
		result=q
		if Post.query.filter(Post.title.contains(q) | Post.body.contains(q)).all():
			posts=Post.query.filter(Post.title.contains(q) | Post.body.contains(q)).all()
		else:
			posts="0"
	else:
		posts = Post.query.order_by(Post.created.desc())
	tags =Tag.query.all()
	return render_template('posts/index.html', posts=posts, tags=tags, result=result)

@posts.route('/<slug>')
def post_detail(slug):
	post = Post.query.filter(Post.slug==slug).first()
	tags = post.tags
	#date = datetime.fromtimestamp(post.created)
	return render_template('posts/post_detail.html', post=post, tags=tags)

@posts.route('/tag/<slug>')
def tag_detail(slug):
	tag = Tag.query.filter(Tag.slug==slug).first()
	posts = tag.posts.all()
	return render_template('posts/tag_detail.html', tag=tag, posts=posts)

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
Создать новый пост
{% endblock %}

{% block content_title %}
Создать новый пост
{% endblock %}

{% block content %}
<div class='col-md-6'>
	<form action="{{ url_for('posts.create_post') }}" method="POST">
		{% for field in form %}
		<div class="form-group">
			{{ field.label(class='control-label') }}
			{{ field(class='form-control') }}
		</div>
		{% endfor %}
		Теги: 
		{% for tag in tags %}
		<input type="radio" id="choice" value={{ tag.name }}>
		<label for="choice"><span class="badge badge-primary">{{ tag.name }} </span></label>
		{% endfor %}
		<br><br>
		<button type="submit" class="btn btn-success">Создать</button>
	</form>
</div>
{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
Посты
{% endblock %}

{% block content_title %}
	{% if result=="null" %}
		Посты
		{% else %}
		{% if posts=="0" %}
			<span class="badge badge-danger">По зaпросу <i>"{{ result }}"</i> постов не найдено!</span>
		{% else %}
			Посты по запросу <i>"{{ result }}"</i>:
		{% endif %}
	{% endif %}
{% endblock %}

{% block content %}

	{% for post in posts %}
		{% if posts!="0" %}
			<a href="{{ url_for('posts.post_detail', slug=post.slug) }}"> {{ post.title }} </a> 
			<hr>
		{% endif %}
	{% endfor %}

	<br>
	Поиск по тегам: 
	{% for tag in tags %}
		<a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"> <span class="badge badge-primary">{{ tag.name }} </span> </a>
	{% endfor %}
{% endblock %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content_title %}
{{ post.title }}
<br>
	<h5><div class="tags">
		{% for tag in tags %}
		<a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"><span class="badge badge-primary">{{ tag.name }}</span></a>	
		{% endfor %}
	</div></h5>
{% endblock %}

{% block content %}
{{ post.body }}
{% endblock %}

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
Посты по тегу "{{ tag.name }}"
{% endblock %}

{% block content_title %}
Посты по тегу <span class="badge badge-primary">{{ tag.name }}</span>
{% endblock %}

{% block content %}
	{% for post in posts %}
		<div class="post">
			<a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
		</div>
		<hr>
	{% endfor %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>

		{% block title %}
		{% endblock %} | SimpleBlog

	</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/for_footer.css') }}">

</head>
<body>
	<div class='wrapper'>
		<div class='content'>

			<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
				<a class="navbar-brand" href="{{ url_for('index') }}"><img  src="{{ url_for('static', filename='favicon.ico') }}" alt="Главная" height="30"></a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item active">

							<a class="nav-link" href="{{ url_for('posts.index') }}">Блог <span class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('posts.create_post') }}">Создать пост</a>
						</li>
					</ul>  
					<form class="form-inline my-2 my-lg-0" method="GET">
						<input class="form-control mr-sm-2" type="text" placeholder="Поиск" name="q" value="{{ request.args.get('q','') }}">
						<button class="btn btn-outline-primary" type="submit">Поиск</button>
					</form>
				</div>
			</nav>

			<div class="container">
				<br>
				<div class="row">
					<h1>
						{% block content_title %}
						{% endblock %}
					</h1>
				</div>
				<hr>
				{% block content %}
				{% endblock %}

			</div>
		</div>

		<div class="footer">
			<footer>
				<div class="footer-copyright text-center py-3">© 2018 Copyright:
					<a href="https://vk.com/4heck"> SimpleBlog.com</a>
				</div>
			</footer>
		</div>
	</div>

</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
Главная
{% endblock %}

{% block content_title %}
Simple Blog
{% endblock %}

{% block content %}
<div class="jumbotron">
	<h1 class="display-4">Привет, мир!</h1>
	<p class="lead">Мы - блог о разработке, администрировании, дизайну, управлению, маркетингу и многом другом :)</p>
	<hr class="my-4">
	<p>Кликай на кнопку и читай все самое интересное из мира гаджетов, интернета и технологий</p>
	<a class="btn btn-primary btn-lg" href="{{ url_for('posts.index') }}" role="button">Читать посты</a>
</div>
{% endblock %}